version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 023756939836.dkr.ecr.ap-northeast-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 023756939836.dkr.ecr.ap-northeast-1.amazonaws.com
      - docker build -t sample:latest .
      - docker tag sample:latest 023756939836.dkr.ecr.ap-northeast-1.amazonaws.com/sample:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 023756939836.dkr.ecr.ap-northeast-1.amazonaws.com/sample:latest
      - echo Writing image definitions file...
      - printf '[{"name":"angular","imageUri":"%s"}]' 023756939836.dkr.ecr.ap-northeast-1.amazonaws.com/sample:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
